# Generated by Django 5.2.8 on 2026-08-03 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='experience_letters/')),
                ('content', models.TextField(blank=True, default='')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_letters', to='employees.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_experience_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience Letter',
                'verbose_name_plural': 'Experience Letters',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_working_day', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('is_relieved', models.BooleanField(default=False)),
                ('relieved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resignations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Resignation',
                'verbose_name_plural': 'Resignations',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='FullAndFinal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('final_settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_dues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assets_returned', models.BooleanField(default=False)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('access_revoked', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_fnf', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_and_final', to='employees.employee')),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_and_final', to='exit_management.resignation')),
            ],
            options={
                'verbose_name': 'Full and Final Settlement',
                'verbose_name_plural': 'Full and Final Settlements',
            },
        ),
        migrations.CreateModel(
            name='ExitApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('comments', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_approvals', to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='exit_management.resignation')),
            ],
            options={
                'verbose_name': 'Exit Approval',
                'verbose_name_plural': 'Exit Approvals',
                'ordering': ['level', '-created_at'],
            },
        ),
    ]
