# Generated by Django 5.2.16 on 2026-08-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('SIM_CARD', 'SIM Card'), ('ID_CARD', 'ID Card'), ('ACCESSORIES', 'Accessories')], max_length=30),
        ),
    ]
