# Generated by Django 5.2.16 on 2026-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='request_type',
            field=models.CharField(choices=[('ALLOCATION', 'Allocation'), ('RETURN', 'Return')], default='ALLOCATION', max_length=20),
        ),
    ]
