# Generated by Django 5.2.8 on 2026-08-03 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern'), ('PROBATION', 'Probation')], default='FULL_TIME', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_NOTICE', 'On Notice'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('date_of_joining', models.DateField()),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('work_email', models.EmailField(blank=True, default='', max_length=254)),
                ('employee_code', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-date_of_joining'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('CORRESPONDENCE', 'Correspondence')], max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee Address',
                'verbose_name_plural': 'Employee Addresses',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION', 'Education Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('OFFER_LETTER', 'Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('SALARY_SLIP', 'Salary Slip'), ('RELIEVING', 'Relieving Letter'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='employees/documents/')),
                ('description', models.TextField(blank=True, default='')),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('university', models.CharField(blank=True, default='', max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_highest', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee Education',
                'verbose_name_plural': 'Employee Education',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee Emergency Contact',
                'verbose_name_plural': 'Employee Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary_drawn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, default='', max_length=255)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee Experience',
                'verbose_name_plural': 'Employee Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='', max_length=20)),
                ('nationality', models.CharField(blank=True, default='', max_length=50)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('religion', models.CharField(blank=True, default='', max_length=50)),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('mother_name', models.CharField(blank=True, default='', max_length=255)),
                ('spouse_name', models.CharField(blank=True, default='', max_length=255)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=20)),
                ('passport_number', models.CharField(blank=True, default='', max_length=50)),
                ('driving_license', models.CharField(blank=True, default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
            ],
            options={
                'verbose_name': 'Employee Personal Info',
                'verbose_name_plural': 'Employee Personal Info',
            },
        ),
    ]
