# Generated by Django 5.2.16 on 2026-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocuments',
            name='document_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('RESUME', 'Resume'), ('OFFER_LETTER', 'Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('EXPERIENCE', 'Experience Letter'), ('EDUCATION', 'Education Certificate'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
