# Generated by Django 5.2.16 on 2026-08-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeedocuments_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
